-- Student council communication MVP.
-- Run this file once in the Supabase SQL editor before deploying the feature.

create extension if not exists pgcrypto;

create table if not exists public.student_council_settings (
  id text primary key,
  feature_enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid null references public.profiles(id) on delete set null,
  constraint student_council_settings_singleton check (id = 'global')
);

insert into public.student_council_settings (id, feature_enabled)
values ('global', true)
on conflict (id) do update
set
  feature_enabled = excluded.feature_enabled,
  updated_at = now();

create table if not exists public.student_council_posts (
  id uuid primary key default gen_random_uuid(),
  category text not null,
  title text not null,
  summary text not null default '',
  body text not null default '',
  target_audience text not null default '전교생',
  action_required text null,
  decision_reason text null,
  department text null,
  event_date timestamptz null,
  deadline timestamptz null,
  meeting_date timestamptz null,
  discussion_topics text null,
  opinions text null,
  decision text null,
  next_schedule text null,
  progress_stage text null,
  status text not null default 'draft',
  is_pinned boolean not null default false,
  is_published boolean not null default false,
  created_by uuid not null references public.profiles(id) on delete restrict,
  updated_by uuid null references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz null,
  constraint student_council_posts_category_check
    check (category in ('notice', 'council', 'activity')),
  constraint student_council_posts_status_check
    check (status in ('draft', 'published', 'in_progress', 'scheduled', 'completed', 'closed')),
  constraint student_council_posts_title_check
    check (char_length(btrim(title)) between 2 and 160)
);

create table if not exists public.student_council_acknowledgements (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.student_council_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  acknowledged_at timestamptz not null default now(),
  constraint student_council_acknowledgements_unique unique (post_id, user_id)
);

create table if not exists public.student_council_post_views (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.student_council_posts(id) on delete cascade,
  viewer_id uuid null references public.profiles(id) on delete set null,
  viewed_at timestamptz not null default now()
);

create index if not exists student_council_posts_public_list_idx
  on public.student_council_posts (is_published, is_pinned desc, published_at desc);

create index if not exists student_council_posts_category_idx
  on public.student_council_posts (category, is_published, published_at desc);

create index if not exists student_council_acknowledgements_post_idx
  on public.student_council_acknowledgements (post_id, acknowledged_at desc);

create index if not exists student_council_post_views_post_idx
  on public.student_council_post_views (post_id, viewed_at desc);

create or replace function public.student_council_set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists student_council_posts_updated_at on public.student_council_posts;
create trigger student_council_posts_updated_at
before update on public.student_council_posts
for each row execute function public.student_council_set_updated_at();

create or replace function public.is_student_council_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and role = 'admin'
  );
$$;

create or replace function public.student_council_feature_enabled()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select feature_enabled from public.student_council_settings where id = 'global'),
    false
  );
$$;

revoke all on function public.is_student_council_admin() from public;
revoke all on function public.student_council_feature_enabled() from public;
grant execute on function public.is_student_council_admin() to authenticated, service_role;
grant execute on function public.student_council_feature_enabled() to authenticated, service_role;

alter table public.student_council_settings enable row level security;
alter table public.student_council_posts enable row level security;
alter table public.student_council_acknowledgements enable row level security;
alter table public.student_council_post_views enable row level security;

revoke all on table public.student_council_settings from anon, authenticated;
revoke all on table public.student_council_posts from anon, authenticated;
revoke all on table public.student_council_acknowledgements from anon, authenticated;
revoke all on table public.student_council_post_views from anon, authenticated;

grant select (feature_enabled) on public.student_council_settings to authenticated;
grant update (feature_enabled) on public.student_council_settings to authenticated;
grant select, insert, update, delete on public.student_council_posts to authenticated;
grant select, insert on public.student_council_acknowledgements to authenticated;
grant select on public.student_council_post_views to authenticated;

grant all on table public.student_council_settings to service_role;
grant all on table public.student_council_posts to service_role;
grant all on table public.student_council_acknowledgements to service_role;
grant all on table public.student_council_post_views to service_role;
grant usage, select on all sequences in schema public to service_role;

drop policy if exists "student_council_settings_authenticated_read" on public.student_council_settings;
drop policy if exists "student_council_settings_admin_update" on public.student_council_settings;
drop policy if exists "student_council_posts_visible_read" on public.student_council_posts;
drop policy if exists "student_council_posts_admin_insert" on public.student_council_posts;
drop policy if exists "student_council_posts_admin_update" on public.student_council_posts;
drop policy if exists "student_council_posts_admin_delete" on public.student_council_posts;
drop policy if exists "student_council_acknowledgements_own_or_admin_read" on public.student_council_acknowledgements;
drop policy if exists "student_council_acknowledgements_own_insert" on public.student_council_acknowledgements;
drop policy if exists "student_council_post_views_admin_read" on public.student_council_post_views;

create policy "student_council_settings_authenticated_read"
on public.student_council_settings
for select
to authenticated
using (true);

create policy "student_council_settings_admin_update"
on public.student_council_settings
for update
to authenticated
using ((select public.is_student_council_admin()))
with check ((select public.is_student_council_admin()));

create policy "student_council_posts_visible_read"
on public.student_council_posts
for select
to authenticated
using (
  (select public.is_student_council_admin())
  or (
    (select public.student_council_feature_enabled())
    and is_published = true
  )
);

create policy "student_council_posts_admin_insert"
on public.student_council_posts
for insert
to authenticated
with check ((select public.is_student_council_admin()));

create policy "student_council_posts_admin_update"
on public.student_council_posts
for update
to authenticated
using ((select public.is_student_council_admin()))
with check ((select public.is_student_council_admin()));

create policy "student_council_posts_admin_delete"
on public.student_council_posts
for delete
to authenticated
using ((select public.is_student_council_admin()));

create policy "student_council_acknowledgements_own_or_admin_read"
on public.student_council_acknowledgements
for select
to authenticated
using (
  user_id = (select auth.uid())
  or (select public.is_student_council_admin())
);

create policy "student_council_acknowledgements_own_insert"
on public.student_council_acknowledgements
for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.student_council_posts post
    where post.id = student_council_acknowledgements.post_id
      and post.is_published = true
      and (
        (select public.student_council_feature_enabled())
        or (select public.is_student_council_admin())
      )
  )
);

create policy "student_council_post_views_admin_read"
on public.student_council_post_views
for select
to authenticated
using ((select public.is_student_council_admin()));

comment on table public.student_council_settings is 'Singleton feature flag for the student council area.';
comment on table public.student_council_posts is 'Unified student council posts differentiated by category.';
comment on table public.student_council_acknowledgements is 'One acknowledgement per user and student council post.';
comment on table public.student_council_post_views is 'Server-recorded detail page views; readable only by admins.';
